package static

const (
	GRAFANA_TOOLS_CLI_USER     string = "GRAFANA_TOOLS_CLI_USER"
	GRAFANA_TOOLS_CLI_PASSWORD string = "GRAFANA_TOOLS_CLI_PASSWORD"
	GRAFANA_TOOLS_CLI_URL      string = "GRAFANA_TOOLS_CLI_URL"
)
